project_environment
channels:
  - defaults
dependencies:
  - python=3.10.12  # Adjust according to the major version you confirmed earlier
  - pip
  - pip:
    - torch==2.4.1+cu121
    - torchvision==0.19.1+cu121
    - pandas==2.2.2
    - matplotlib==3.7.1
    - numpy==1.26.4
    - timm==1.0.11
    - scikit-learn==1.1.2  # Assuming you need scikit-learn for sklearn-pandas
    - sklearn-pandas==2.2.0
